### ISSUE TITLE
Erro ao gravar o código - avrdude: Error: Could not find USBtiny device (0x2341/0xc9f)

### ISSUE THREAD

**Issue by felipefernandes** [FBSeletronica/Franzininho#18]
Instalei o driver e a IDE Arduino no Windows, escrevi o programa simplezinho (modificando  hello world), eu aperto o botão RESET antes de fazer o upload, a Franzininho troca o modo de piscar o led, mas ao invés de mudar modo de piscar (programa novo), eu recebo o erro **avrdude: Error: Could not find USBtiny device (0x2341/0xc9f)** na IDE do Arduino. Como posso resolver isso?

**Comment by FBSeletronica** [comment]
Felipe, verifique no gerenciador de tarefas se a placa está sendo reconhecida pelo windows. Parece ser um erro de driver
