### ISSUE TITLE
Novo recurso - Simulador grátis para Franzininho

### ISSUE THREAD

**Issue by matititam** [FBSeletronica/Franzininho#26]
Olá

dia bom

temos um simulador online gratuito para placas Franzininho. O link está aqui: https://docs.wokwi.com/parts/wokwi-franzininho#simulator-examples

![Wokwi Franzininho online SImulator NTC and OLED display](https://user-images.githubusercontent.com/68117142/123591831-1b0c5e00-d80a-11eb-82d1-c0c44db833a7.gif)
![Wokwi Franzininho online SImulator Franzininho Clock1](https://user-images.githubusercontent.com/68117142/123591843-1d6eb800-d80a-11eb-8283-edc487c97413.gif)
![Wokwi Franzininho online SImulator](https://user-images.githubusercontent.com/68117142/123591846-1f387b80-d80a-11eb-8ba0-e06a6b3a0727.gif)

Teremos o maior prazer em compartilhar mais exemplos. Muitas pessoas já estão usando este simulador. Acredito fortemente que isso ajudará todos os seus leitores. Por favor, me diga se eu posso criar um PR para adicionar o link para o simulador Franzininho!
Obrigada!

**Comment by FBSeletronica** [comment]
Opa. Estamos trabalhando junto ao wokwi para esse simulador. Fique a vontade para enviar o link em nossa documentação. 

Muito obrigado
